deploy:
  needs: Build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.528757794050 }}:role/${{ secrets.userx2025 }} # Reemplaza con el ARN de tu rol
        aws-region: ${{ secrets.us-east-2 }}
        role-session-name: GitHubActions
        web-identity-token: ${{ steps.oidc.outputs.value }}

    - name: Get OIDC token
      id: oidc
      uses: actions/github-script@v7
      outputs:
        value: ${{ steps.oidc.outputs.value }}
      with:
        script: |
          core.setOutput('value', await github.getIDToken({}))

    - name: Deploy to S3
      uses: JavierCortejoso/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
        aws_bucket: ${{ secrets.userx2025 }}
        # Las credenciales ya están configuradas por la acción aws-actions/configure-aws-credentials
        aws_region: ${{ secrets.us-east-2 }}
